# Generated by Django 2.1.7 on 2019-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20190224_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
