# Generated by Django 2.1.7 on 2019-02-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_milkreceive'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Customer')),
                ('milk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.MilkReceive')),
            ],
        ),
        migrations.RenameModel(
            old_name='Entry',
            new_name='EntryClient',
        ),
    ]
