# Generated by Django 2.1.7 on 2019-02-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20190224_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryclient',
            name='milk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.MilkReceive'),
        ),
        migrations.AlterField(
            model_name='entrycustomer',
            name='milk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Milk'),
        ),
    ]
